In [17]:
import pandas as pd

# Load dataset
df = pd.read_csv("dataset/ransomware_data.csv")

# Show first 5 rows
df.head()

,hash,millisecond,classification,state,usage_counter,prio,static_prio,normal_prio,policy,vm_pgoff,...,nivcsw,min_flt,maj_flt,fs_excl_counter,lock,utime,stime,gtime,cgtime,signal_nvcsw
0,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,0,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0
1,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,1,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0
2,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,2,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0
3,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,3,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0
4,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,4,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0

In [18]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:\n")
print(df.columns)

print("\nDataset Information:\n")
print(df.info())

Dataset Shape: (100000, 35)

Column Names:

Index(['hash', 'millisecond', 'classification', 'state', 'usage_counter',
       'prio', 'static_prio', 'normal_prio', 'policy', 'vm_pgoff',
       'vm_truncate_count', 'task_size', 'cached_hole_size', 'free_area_cache',
       'mm_users', 'map_count', 'hiwater_rss', 'total_vm', 'shared_vm',
       'exec_vm', 'reserved_vm', 'nr_ptes', 'end_data', 'last_interval',
       'nvcsw', 'nivcsw', 'min_flt', 'maj_flt', 'fs_excl_counter', 'lock',
       'utime', 'stime', 'gtime', 'cgtime', 'signal_nvcsw'],
      dtype='object')

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 35 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   hash               100000 non-null  object
 1   millisecond        100000 non-null  int64
 2   classification     100000 non-null  object
 3   state              100000 non-null  int64
 4   usage_counter      100000 non-null  int64
 5   prio               100000 non-null  int64
 6   static_prio        100000 non-null  int64
 7   normal_prio        100000 non-null  int64
 8   policy             100000 non-null  int64
 9   vm_pgoff           100000 non-null  int64
 10  vm_truncate_count  100000 non-null  int64
 11  task_size          100000 non-null  int64
 12  cached_hole_size   100000 non-null  int64
 13  free_area_cache    100000 non-null  int64
 14  mm_users           100000 non-null  int64
 15  map_count          100000 non-null  int64
 16  hiwater_rss        100000 non-null  int64
 17  total_vm           100000 non-null  int64
 18  shared_vm          100000 non-null  int64
 19  exec_vm            100000 non-null  int64
 20  reserved_vm        100000 non-null  int64
 21  nr_ptes            100000 non-null  int64
 22  end_data           100000 non-null  int64
 23  last_interval      100000 non-null  int64
 24  nvcsw              100000 non-null  int64
 25  nivcsw             100000 non-null  int64
 26  min_flt            100000 non-null  int64
 27  maj_flt            100000 non-null  int64
 28  fs_excl_counter    100000 non-null  int64
 29  lock               100000 non-null  int64
 30  utime              100000 non-null  int64
 31  stime              100000 non-null  int64
 32  gtime              100000 non-null  int64
 33  cgtime             100000 non-null  int64
 34  signal_nvcsw       100000 non-null  int64
dtypes: int64(33), object(2)
memory usage: 26.7+ MB
None

In [19]:
df.head()

,hash,millisecond,classification,state,usage_counter,prio,static_prio,normal_prio,policy,vm_pgoff,...,nivcsw,min_flt,maj_flt,fs_excl_counter,lock,utime,stime,gtime,cgtime,signal_nvcsw
0,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,0,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0
1,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,1,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0
2,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,2,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0
3,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,3,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0
4,42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...,4,malware,0,0,3069378560,14274,0,0,0,...,0,0,120,0,3204448256,380690,4,0,0,0

In [20]:
print(df.isnull().sum())
# Drop rows with missing values

hash                 0
millisecond          0
classification       0
state                0
usage_counter        0
prio                 0
static_prio          0
normal_prio          0
policy               0
vm_pgoff             0
vm_truncate_count    0
task_size            0
cached_hole_size     0
free_area_cache      0
mm_users             0
map_count            0
hiwater_rss          0
total_vm             0
shared_vm            0
exec_vm              0
reserved_vm          0
nr_ptes              0
end_data             0
last_interval        0
nvcsw                0
nivcsw               0
min_flt              0
maj_flt              0
fs_excl_counter      0
lock                 0
utime                0
stime                0
gtime                0
cgtime               0
signal_nvcsw         0
dtype: int64

In [21]:
df = df.drop("hash", axis=1)

In [8]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["classification"] = encoder.fit_transform(df["classification"])

print(df["classification"].value_counts())

classification
1    50000
0    50000
Name: count, dtype: int64

In [9]:
X = df.drop("classification", axis=1)

y = df["classification"]

print(X.shape)
print(y.shape)

(100000, 33)
(100000,)

In [10]:
feature_names = X.columns.tolist()

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(80000, 33)
(20000, 33)

In [12]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully

In [13]:
predictions = model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("Accuracy:", accuracy_score(y_test, predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predictions))

print("\nClassification Report:")
print(classification_report(y_test, predictions))

Accuracy: 1.0

Confusion Matrix:
[[10030     0]
 [    0  9970]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     10030
           1       1.00      1.00      1.00      9970

    accuracy                           1.00     20000
   macro avg       1.00      1.00      1.00     20000
weighted avg       1.00      1.00      1.00     20000

In [15]:
import joblib
joblib.dump(
    {
        "model": model,
        "feature_names": feature_names
    },
    "model/ransomware_model.pkl"
)

['model/ransomware_model.pkl']